class Countries {
  List<Country> countries = getCountries();
  static List<Country> getCountries() {
    return data.map<Country>(Country.fromJSON).toList();
  }
}

class Country {
  final String name, flag, code;
  final List states;
  const Country(
      {required this.name,
      required this.flag,
      required this.code,
      required this.states});

  static Country fromJSON(json) => Country(
      name: json['name'],
      flag: json['flag'],
      code: json['code'],
      states: json["states"]);
}

// !IMPORTANT! ****ADD ALL COUNTRIES WITH THEIR FLAGS****
// Country JSON data
const data = [
  {
    "name": "Afghanistan",
    "flag": "af.png",
    "code": "93",
    "states": [
      "Ghazni",
      "Badghis",
      "Bamyan",
      "Helmand",
      "Zabul",
      "Baghlan",
      "Kunar",
      "Paktika",
      "Khost",
      "Kapisa",
      "Nuristan",
      "Panjshir",
      "Nangarhar",
      "Samangan",
      "Balkh",
      "Sar-e Pol",
      "Jowzjan",
      "Herat",
      "Ghōr",
      "Faryab",
      "Kandahar",
      "Laghman",
      "Daykundi",
      "Takhar",
      "Paktia",
      "Parwan",
      "Nimruz",
      "Logar",
      "Urozgan",
      "Farah",
      "Kunduz Province",
      "Badakhshan",
      "Kabul",
    ],
  },
  {
    "name": "Albania",
    "flag": "al.png",
    "code": "335",
    "states": [
      "Skrapar District",
      "Kavajë District",
      "Lezhë District",
      "Librazhd District",
      "Korçë District",
      "Elbasan",
      "Lushnjë District",
      "Has District",
      "Kukës",
      "Malësi e Madhe District",
      "Berat",
      "Gjirokastër",
      "Dibër District",
      "Pogradec District",
      "Bulqizë District",
      "Devoll District",
      "Lezhë",
      "Dibër",
      "Shkodër",
      "Kuçovë District",
      "Vlorë District",
      "Krujë District",
      "Tirana",
      "Tepelenë District",
      "Gramsh District",
      "Delvinë District",
      "Peqin District",
      "Pukë District",
      "Gjirokastër District",
      "Kurbin District",
      "Kukës District",
      "Sarandë District",
      "Përmet District",
      "Shkodër District",
      "Fier District",
      "Kolonjë District",
      "Berat District",
      "Korçë",
      "Fier",
      "Durrës",
      "Tirana District",
      "Vlorë",
      "Mat District",
      "Tropojë District",
      "Mallakastër District",
      "Mirditë District",
      "Durrës District",
    ]
  },
  {
    "name": "Algeria",
    "flag": "dz.png",
    "code": "213",
    "states": [
      "Djelfa",
      "El Oued",
      "El Tarf",
      "Oran",
      "Naama",
      "Annaba",
      "Bouïra",
      "Chlef",
      "Tiaret",
      "Tlemcen",
      "Béchar",
      "Médéa",
      "Skikda",
      "Blida",
      "Illizi",
      "Jijel",
      "Biskra",
      "Tipasa",
      "Bordj Bou Arréridj",
      "Tébessa",
      "Adrar",
      "Aïn Defla",
      "Tindouf",
      "Constantine",
      "Aïn Témouchent",
      "Saïda",
      "Mascara",
      "Boumerdès",
      "Khenchela",
      "Ghardaïa",
      "Béjaïa",
      "El Bayadh",
      "Relizane",
      "Tizi Ouzou",
      "Mila",
      "Tissemsilt",
      "M'Sila",
      "Tamanghasset",
      "Oum El Bouaghi",
      "Guelma",
      "Laghouat",
      "Ouargla",
      "Mostaganem",
      "Sétif",
      "Batna",
      "Souk Ahras",
      "Algiers",
      "Sidi Bel Abbès",
      "El M'ghair",
      "El Menia",
      "Ouled Djellal",
      "Bordj Baji Mokhtar",
      "Béni Abbès",
      "Timimoun",
      "Touggourt",
      "Djanet",
      "In Salah",
      "In Guezzam",
    ]
  },
  {
    "name": "Andorra",
    "flag": "ad.png",
    "code": "376",
    "states": [
      "Encamp",
      "Andorra la Vella",
      "Canillo",
      "Sant Julià de Lòria",
      "Ordino",
      "Escaldes-Engordany",
      "La Massana",
    ]
  },
  {
    "name": "Angola",
    "flag": "ao.png",
    "code": "244",
    "states": [
      "Bié Province",
      "Huambo Province",
      "Zaire Province",
      "Cunene Province",
      "Cuanza Sul",
      "Cuanza Norte Province",
      "Benguela Province",
      "Moxico Province",
      "Lunda Sul Province",
      "Bengo Province",
      "Luanda Province",
      "Lunda Norte Province",
      "Uíge Province",
      "Huíla Province",
      "Cuando Cubango Province",
      "Malanje Province",
      "Cabinda Province",
    ]
  },
  {
    "name": "Argentina",
    "flag": "ar.png",
    "code": "54",
    "states": [
      "San Juan",
      "Santiago del Estero",
      "San Luis",
      "Tucumán",
      "Corrientes",
      "Río Negro",
      "Chaco",
      "Santa Fe",
      "Córdoba",
      "Salta",
      "Misiones",
      "Jujuy",
      "Mendoza",
      "Catamarca",
      "Neuquén",
      "Santa Cruz",
      "Tierra del Fuego",
      "Chubut",
      "Formosa",
      "La Rioja",
      "Entre Ríos",
      "La Pampa",
      "Buenos Aires",
      "Ciudad Autónoma de Buenos Aires",
    ],
  },
  {
    "name": "Armenia",
    "flag": "am.png",
    "code": "374",
    "states": [
      "Aragatsotn Region",
      "Ararat Province",
      "Vayots Dzor Region",
      "Armavir Region",
      "Syunik Province",
      "Gegharkunik Province",
      "Lori Region",
      "Yerevan",
      "Shirak Region",
      "Tavush Region",
      "Kotayk Region",
    ]
  },
  {
    "name": "Australia",
    "flag": "au.png",
    "code": "61",
    "states": [
      "Victoria",
      "South Australia",
      "Queensland",
      "Western Australia",
      "Tasmania",
      "New South Wales",
    ]
  },
  {
    "name": "Austria",
    "flag": "at.png",
    "code": "43",
    "states": [
      "Carinthia",
      "Upper Austria",
      "Styria",
      "Vienna",
      "Salzburg",
      "Burgenland",
      "Vorarlberg",
      "Tyrol",
      "Lower Austria",
    ],
  },
  {
    "name": "Azerbaijan",
    "flag": "az.png",
    "code": "994",
    "states": [
      "Shaki",
      "Tartar District",
      "Shirvan",
      "Qazakh District",
      "Sadarak District",
      "Yevlakh District",
      "Khojali District",
      "Kalbajar District",
      "Qakh District",
      "Fizuli District",
      "Astara District",
      "Shamakhi District",
      "Neftchala District",
      "Goychay",
      "Bilasuvar District",
      "Tovuz District",
      "Ordubad District",
      "Sharur District",
      "Samukh District",
      "Khizi District",
      "Yevlakh",
      "Ujar District",
      "Absheron District",
      "Lachin District",
      "Qabala District",
      "Agstafa District",
      "Imishli District",
      "Salyan District",
      "Lerik District",
      "Agsu District",
      "Qubadli District",
      "Kurdamir District",
      "Yardymli District",
      "Goranboy District",
      "Baku",
      "Agdash District",
      "Beylagan District",
      "Masally District",
      "Oghuz District",
      "Saatly District",
      "Lankaran District",
      "Agdam District",
      "Balakan District",
      "Dashkasan District",
      "Nakhchivan Autonomous Republic",
      "Quba District",
      "Ismailli District",
      "Sabirabad District",
      "Zaqatala District",
      "Kangarli District",
      "Martuni",
      "Barda District",
      "Jabrayil District",
      "Hajigabul District",
      "Julfa District",
      "Gobustan District",
      "Goygol District",
      "Babek District",
      "Zardab District",
      "Aghjabadi District",
      "Jalilabad District",
      "Shahbuz District",
      "Mingachevir",
      "Zangilan District",
      "Sumqayit",
      "Shamkir District",
      "Siazan District",
      "Ganja",
      "Shaki District",
      "Lankaran",
      "Qusar District",
      "Gədəbəy",
      "Khachmaz District",
      "Shabran District",
      "Shusha District",
    ],
  },
  {
    "name": "Bahamas",
    "flag": "bs.png",
    "code": "1",
    "states": [
      "Berry Islands",
      "Nichollstown & Berry Islands",
      "Green Turtle Cay",
      "Central Eleuthera",
      "Governor's Harbour",
      "High Rock",
      "West Grand Bahama",
      "Rum Cay District",
      "Acklins",
      "North Eleuthera",
      "Central Abaco",
      "Marsh Harbour",
      "Black Point",
      "Sandy Point",
      "South Eleuthera",
      "South Abaco",
      "Inagua",
      "Long Island",
      "Cat Island",
      "Exuma",
      "Harbour Island",
      "East Grand Bahama",
      "Ragged Island",
      "North Abaco",
      "North Andros",
      "Kemps Bay",
      "Fresh Creek",
      "San Salvador & Rum Cay",
      "Crooked Island",
      "South Andros",
      "Rock Sound",
      "Hope Town",
      "Mangrove Cay",
      "Freeport",
      "San Salvador Island",
      "Acklins & Crooked Islands",
      "Bimini",
      "Spanish Wells",
      "Central Andros",
      "Grand Cay",
      "Mayaguana District",
      "New Providence",
    ]
  },
  {
    "name": "Bahrain",
    "flag": "bh.png",
    "code": "973",
    "states": [
      "Capital",
      "Southern",
      "Northern",
      "Muharraq",
      "Central",
    ]
  },
  {
    "name": "Bangladesh",
    "flag": "bd.png",
    "code": "880",
    "states": [
      "Rangpur Division",
      "Cox's Bazar District",
      "Bandarban District",
      "Rajshahi Division",
      "Pabna District",
      "Sherpur District",
      "Bhola District",
      "Jessore District",
      "Mymensingh Division",
      "Rangpur District",
      "Dhaka Division",
      "Chapai Nawabganj District",
      "Faridpur District",
      "Comilla District",
      "Netrokona District",
      "Sylhet Division",
      "Mymensingh District",
      "Sylhet District",
      "Chandpur District",
      "Narail District",
      "Narayanganj District",
      "Dhaka District",
      "Nilphamari District",
      "Rajbari District",
      "Kushtia District",
      "Khulna Division",
      "Meherpur District",
      "Patuakhali District",
      "Jhalokati District",
      "Kishoreganj District",
      "Lalmonirhat District",
      "Sirajganj District",
      "Tangail District",
      "Dinajpur District",
      "Barguna District",
      "Chittagong District",
      "Khagrachari District",
      "Natore District",
      "Chuadanga District",
      "Jhenaidah District",
      "Munshiganj District",
      "Pirojpur District",
      "Gopalganj District",
      "Kurigram District",
      "Moulvibazar District",
      "Gaibandha District",
      "Bagerhat District",
      "Bogra District",
      "Gazipur District",
      "Satkhira District",
      "Panchagarh District",
      "Shariatpur District",
      "Bahadia",
      "Chittagong Division",
      "Thakurgaon District",
      "Habiganj District",
      "Joypurhat District",
      "Barisal Division",
      "Jamalpur District",
      "Rangamati Hill District",
      "Brahmanbaria District",
      "Khulna District",
      "Sunamganj District",
      "Naogaon District",
      "Noakhali District",
      "Feni District",
      "Madaripur District",
      "Barisal District",
      "Lakshmipur District",
    ]
  },
  {
    "name": "Belarus",
    "flag": "by.png",
    "code": "375",
    "states": [
      "Mogilev Region",
      "Gomel Region",
      "Grodno Region",
      "Minsk Region",
      "Minsk",
      "Brest Region",
      "Vitebsk Region",
    ]
  },
  {
    "name": "Belguim",
    "flag": "be.png",
    "code": "32",
    "states": [
      "Limburg",
      "Flanders",
      "Flemish Brabant",
      "Hainaut",
      "Brussels-Capital Region",
      "East Flanders",
      "Namur",
      "Luxembourg",
      "Wallonia",
      "Antwerp",
      "Walloon Brabant",
      "West Flanders",
      "Liège",
    ]
  },
  {
    "name": "Belize",
    "flag": "bz.png",
    "code": "501",
    "states": [
      "Belize District",
      "Stann Creek District",
      "Corozal District",
      "Toledo District",
      "Orange Walk District",
      "Cayo District",
    ]
  },
  {
    "name": "Benin",
    "flag": "bj.png",
    "code": "229",
    "states": [
      "Collines Department",
      "Kouffo Department",
      "Donga Department",
      "Zou Department",
      "Plateau Department",
      "Mono Department",
      "Atakora Department",
      "Alibori Department",
      "Borgou Department",
      "Atlantique Department",
      "Ouémé Department",
      "Littoral Department",
    ]
  },
  {
    "name": "Bhutan",
    "flag": "bt.png",
    "code": "975",
    "states": [
      "Gasa District",
      "Tsirang District",
      "Wangdue Phodrang District",
      "Haa District",
      "Zhemgang District",
      "Lhuntse District",
      "Punakha District",
      "Trashigang District",
      "Paro District",
      "Dagana District",
      "Chukha District",
      "Bumthang District",
      "Thimphu District",
      "Mongar District",
      "Samdrup Jongkhar District",
      "Pemagatshel District",
      "Trongsa District",
      "Samtse District",
      "Sarpang District",
    ],
  },
  {
    "name": "Bolivia",
    "flag": "bo.png",
    "code": "591",
    "states": [
      "Beni Department",
      "Oruro Department",
      "Santa Cruz Department",
      "Tarija Department",
      "Pando Department",
      "La Paz Department",
      "Cochabamba Department",
      "Chuquisaca Department",
      "Potosí Department",
    ],
  },
  {
    "name": "Bosnia & Herzegovina",
    "flag": "ba.png",
    "code": "387",
    "states": [
      "Brčko District",
      "Tuzla Canton",
      "Central Bosnia Canton",
      "Herzegovina-Neretva Canton",
      "Posavina Canton",
      "Una-Sana Canton",
      "Sarajevo Canton",
      "Federation of Bosnia and Herzegovina",
      "Zenica-Doboj Canton",
      "West Herzegovina Canton",
      "Republika Srpska",
      "Canton 10",
      "Bosnian Podrinje Canton",
    ]
  },
  {
    "name": "Botswana",
    "flag": "bw.png",
    "code": "267",
    "states": [
      "Ngamiland",
      "Ghanzi District",
      "Kgatleng District",
      "Southern District",
      "South-East District",
      "North-West District",
      "Kgalagadi District",
      "Central District",
      "North-East District",
      "Kweneng District",
    ]
  },
  {
    "name": "Brazil",
    "flag": "br.png",
    "code": "55",
    "states": [
      "Rio de Janeiro",
      "Minas Gerais",
      "Amapá",
      "Goiás",
      "Rio Grande do Sul",
      "Bahia",
      "Sergipe",
      "Amazonas",
      "Paraíba",
      "Pernambuco",
      "Alagoas",
      "Piauí",
      "Pará",
      "Mato Grosso do Sul",
      "Mato Grosso",
      "Acre",
      "Rondônia",
      "Santa Catarina",
      "Maranhão",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Rio Grande do Norte",
      "Tocantins",
      "São Paulo",
      "Paraná",
      "Roraima",
    ]
  },
  {
    "name": "Brunei",
    "flag": "bn.png",
    "code": "673",
    "states": [
      "Brunei-Muara District",
      "Belait District",
      "Temburong District",
      "Tutong District",
    ]
  },
  {
    "name": "Bulgaria",
    "flag": "bg.png",
    "code": "359",
    "states": [
      "Gabrovo Province",
      "Smolyan Province",
      "Pernik Province",
      "Montana Province",
      "Vidin Province",
      "Razgrad Province",
      "Blagoevgrad Province",
      "Sliven Province",
      "Plovdiv Province",
      "Kardzhali Province",
      "Kyustendil Province",
      "Haskovo Province",
      "Sofia City Province",
      "Pleven Province",
      "Stara Zagora Province",
      "Silistra Province",
      "Veliko Tarnovo Province",
      "Lovech Province",
      "Vratsa Province",
      "Pazardzhik Province",
      "Ruse Province",
      "Targovishte Province",
      "Burgas Province",
      "Yambol Province",
      "Varna Province",
      "Dobrich Province",
      "Sofia Province",
      "Shumen",
    ]
  },
  {
    "name": "Burkina Faso",
    "flag": "bf.png",
    "code": "226",
    "states": [
      "Kénédougou Province",
      "Namentenga Province",
      "Sahel Region",
      "Centre-Ouest Region",
      "Nahouri Province",
      "Passoré Province",
      "Zoundwéogo Province",
      "Sissili Province",
      "Banwa Province",
      "Bougouriba Province",
      "Gnagna Province",
      "Mouhoun",
      "Yagha Province",
      "Plateau-Central Region",
      "Sanmatenga Province",
      "Centre-Nord Region",
      "Tapoa Province",
      "Houet Province",
      "Zondoma Province",
      "Boulgou",
      "Komondjari Province",
      "Koulpélogo Province",
      "Tuy Province",
      "Ioba Province",
      "Centre",
      "Sourou Province",
      "Boucle du Mouhoun Region",
      "Séno Province",
      "Sud-Ouest Region",
      "Oubritenga Province",
      "Nayala Province",
      "Gourma Province",
      "Oudalan Province",
      "Ziro Province",
      "Kossi Province",
      "Kourwéogo Province",
      "Ganzourgou Province",
      "Centre-Sud Region",
      "Yatenga Province",
      "Loroum Province",
      "Bazèga Province",
      "Cascades Region",
      "Sanguié Province",
      "Bam Province",
      "Noumbiel Province",
      "Kompienga Province",
      "Est Region",
      "Léraba Province",
      "Balé Province",
      "Kouritenga Province",
      "Centre-Est Region",
      "Poni Province",
      "Nord Region, Burkina Faso",
      "Hauts-Bassins Region",
      "Soum Province",
      "Comoé Province",
      "Kadiogo Province",
    ]
  },
  {
    "name": "Burundi",
    "flag": "bi.png",
    "code": "257",
    "states": [
      "Rumonge Province",
      "Muyinga Province",
      "Mwaro Province",
      "Makamba Province",
      "Rutana Province",
      "Cibitoke Province",
      "Ruyigi Province",
      "Kayanza Province",
      "Muramvya Province",
      "Karuzi Province",
      "Kirundo Province",
      "Bubanza Province",
      "Gitega Province",
      "Bujumbura Mairie Province",
      "Ngozi Province",
      "Bujumbura Rural Province",
      "Cankuzo Province",
      "Bururi Province",
    ]
  },
  {
    "name": "Cambodia",
    "flag": "kh.png",
    "code": "855",
    "states": [
      "Svay Rieng",
      "Preah Vihear",
      "Prey Veng",
      "Takeo",
      "Battambang",
      "Pursat",
      "Kep",
      "Kampong Chhnang",
      "Pailin",
      "Kampot",
      "Koh Kong",
      "Kandal",
      "Banteay Meanchey",
      "Mondulkiri",
      "Kratie",
      "Oddar Meanchey",
      "Kampong Speu",
      "Sihanoukville",
      "Ratanakiri",
      "Kampong Cham",
      "Siem Reap",
      "Stung Treng",
      "Phnom Penh",
      "Tai Po District",
      "Kampong Thom",
    ]
  },
  {
    "name": "Cameroon",
    "flag": "cm.png",
    "code": "237",
    "states": [
      "Far North",
      "Northwest",
      "Southwest",
      "South",
      "Centre",
      "East",
      "Littoral",
      "Adamawa",
      "West",
      "North",
    ],
  },
  {
    "name": "Canada",
    "flag": "ca.png",
    "code": "1",
    "states": [
      "Ontario",
      "Manitoba",
      "New Brunswick",
      "Yukon",
      "Saskatchewan",
      "Prince Edward Island",
      "Alberta",
      "Quebec",
      "Nova Scotia",
      "British Columbia",
      "Nunavut",
      "Newfoundland and Labrador",
      "Northwest Territories",
    ],
  },
  {
    "name": "Cape Verde",
    "flag": "cv.png",
    "code": "238",
    "states": [
      "Ribeira Brava",
      "Tarrafal",
      "Ribeira Grande de Santiago",
      "Santa Catarina",
      "São Domingos",
      "Mosteiros",
      "Praia",
      "Porto Novo",
      "São Miguel",
      "Maio",
      "Sotavento Islands",
      "São Lourenço dos Órgãos",
      "Barlavento Islands",
      "Santa Catarina do Fogo",
      "Brava",
      "Paul",
      "Sal",
      "Boa Vista",
      "São Filipe",
      "São Vicente",
      "Ribeira Grande",
      "Tarrafal de São Nicolau",
      "Santa Cruz",
    ]
  },
  {
    "name": "Central African Republic",
    "flag": "cf.png",
    "code": "236",
    "states": [
      "Sangha-Mbaéré",
      "Nana-Grébizi Economic Prefecture",
      "Ouham Prefecture",
      "Ombella-M'Poko Prefecture",
      "Lobaye Prefecture",
      "Mambéré-Kadéï",
      "Haut-Mbomou Prefecture",
      "Bamingui-Bangoran Prefecture",
      "Nana-Mambéré Prefecture",
      "Vakaga Prefecture",
      "Bangui",
      "Kémo Prefecture",
      "Basse-Kotto Prefecture",
      "Ouaka Prefecture",
      "Mbomou Prefecture",
      "Ouham-Pendé Prefecture",
      "Haute-Kotto Prefecture",
    ]
  },
  {
    "name": "Chad",
    "flag": "td.png",
    "code": "235",
    "states": [
      "Moyen-Chari",
      "Mayo-Kebbi Ouest",
      "Sila",
      "Hadjer-Lamis",
      "Borkou",
      "Ennedi-Est",
      "Guéra",
      "Lac",
      "Tandjilé",
      "Mayo-Kebbi Est",
      "Wadi Fira",
      "Ouaddaï",
      "Bahr el Gazel",
      "Ennedi-Ouest",
      "Logone Occidental",
      "N'Djamena",
      "Tibesti",
      "Kanem",
      "Mandoul",
      "Batha",
      "Logone Oriental",
      "Salamat",
      "Chari-Baguirmi",
    ]
  },
  {
    "name": "Chile",
    "flag": "cl.png",
    "code": "56",
    "states": [
      "Atacama",
      "Santiago",
      "Coquimbo",
      "La Araucanía",
      "Biobío",
      "Aisén (Aysén)",
      "Arica y Parinacota",
      "Valparaíso",
      "Ñuble",
      "Antofagasta",
      "Maule",
      "Los Ríos",
      "Los Lagos",
      "Magallanes",
      "Tarapacá",
      "O'Higgins",
    ]
  },
  {
    "name": "China",
    "flag": "cn.png",
    "code": "86",
    "states": [
      "Zhejiang",
      "Fujian",
      "Shanghai",
      "Jiangsu",
      "Anhui",
      "Shandong",
      "Jilin",
      "Shanxi",
      "Taiwan",
      "Jiangxi",
      "Beijing",
      "Hunan",
      "Henan",
      "Yunnan",
      "Guizhou",
      "Ningxia Huizu",
      "Xinjiang",
      "Xizang",
      "Heilongjiang",
      "Macau SAR",
      "Hong Kong",
      "Liaoning",
      "Inner Mongolia",
      "Qinghai",
      "Chongqing",
      "Shaanxi",
      "Hainan",
      "Hubei",
      "Gansu",
      "Tianjin",
      "Sichuan",
      "Guangxi Zhuang",
      "Guangdong",
      "Hebei",
    ]
  },
  {
    "name": "Colombia",
    "flag": "co.png",
    "code": "57",
    "states": [
      "Quindío",
      "Cundinamarca",
      "Chocó",
      "Norte de Santander",
      "Meta",
      "Risaralda",
      "Atlántico",
      "Arauca",
      "Guainía",
      "Tolima",
      "Cauca",
      "Vaupés",
      "Magdalena",
      "Caldas",
      "Guaviare",
      "La Guajira",
      "Antioquia",
      "Caquetá",
      "Casanare",
      "Bolívar",
      "Vichada",
      "Amazonas",
      "Putumayo",
      "Nariño",
      "Córdoba",
      "Cesar",
      "San Andrés",
      "Santander",
      "Sucre",
      "Boyacá",
      "Valle del Cauca",
      "Huila",
      "Bogotá D.C.",
    ]
  },
  {
    "name": "Comoros",
    "flag": "km.png",
    "code": "269",
    "states": [
      "Mohéli",
      "Anjouan",
      "Grande Comore",
    ]
  },
  {
    "name": "Costa Rica",
    "flag": "cr.png",
    "code": "506",
    "states": [
      "Guanacaste Province",
      "Puntarenas Province",
      "Provincia de Cartago",
      "Heredia Province",
      "Limón Province",
      "San José Province",
      "Alajuela Province",
    ]
  },
  {
    "name": "Croatia",
    "flag": "hr.png",
    "code": "385",
    "states": [
      "Požega-Slavonia",
      "Split-Dalmatia",
      "Međimurje",
      "Zadar",
      "Dubrovnik-Neretva",
      "Krapina-Zagorje",
      "Šibenik-Knin",
      "Lika-Senj",
      "Virovitica-Podravina",
      "Sisak-Moslavina",
      "Bjelovar-Bilogora",
      "Primorje-Gorski Kotar",
      "Zagreb",
      "Brod-Posavina",
      "Zagreb",
      "Varaždin",
      "Osijek-Baranja",
      "Vukovar-Syrmia",
      "Koprivnica-Križevci",
      "Istria",
      "Karlovac",
    ]
  },
  {
    "name": "Cuba",
    "flag": "cu.png",
    "code": "53",
    "states": [
      "Havana Province",
      "Santiago de Cuba Province",
      "Sancti Spíritus Province",
      "Granma Province",
      "Mayabeque Province",
      "Pinar del Río Province",
      "Isla de la Juventud",
      "Holguín Province",
      "Villa Clara Province",
      "Las Tunas Province",
      "Ciego de Ávila Province",
      "Artemisa Province",
      "Matanzas Province",
      "Guantánamo Province",
      "Camagüey Province",
      "Cienfuegos Province",
    ]
  },
  {
    "name": "Cyprus",
    "flag": "cy.png",
    "code": "357",
    "states": [
      "Keryneia",
      "Lefkoşa",
      "Pafos",
      "Larnaka",
      "Leymasun",
      "Mağusa",
    ]
  },
  {
    "name": "Czech Republic",
    "flag": "cz.png",
    "code": "420",
    "states": [
      "Břeclav",
      "Český Krumlov",
      "Plzeň-město",
      "Brno-venkov",
      "Příbram",
      "Pardubice",
      "Nový Jičín",
      "Náchod",
      "Prostějov",
      "Zlínský kraj",
      "Chomutov",
      "Středočeský kraj",
      "České Budějovice",
      "Rakovník",
      "Frýdek-Místek",
      "Písek",
      "Hodonín",
      "Zlín",
      "Plzeň-sever",
      "Tábor",
      "Brno-město",
      "Svitavy",
      "Vsetín",
      "Cheb",
      "Olomouc",
      "Kraj Vysočina",
      "Ústecký kraj",
      "Prachatice",
      "Trutnov",
      "Hradec Králové",
      "Karlovarský kraj",
      "Nymburk",
      "Rokycany",
      "Ostrava-město",
      "Karviná",
      "Pardubický kraj",
      "Olomoucký kraj",
      "Liberec",
      "Klatovy",
      "Uherské Hradiště",
      "Kroměříž",
      "Sokolov",
      "Semily",
      "Třebíč",
      "Praha, Hlavní město",
      "Ústí nad Labem",
      "Moravskoslezský kraj",
      "Liberecký kraj",
      "Jihomoravský kraj",
      "Karlovy Vary",
      "Litoměřice",
      "Praha-východ",
      "Plzeňský kraj",
      "Plzeň-jih",
      "Děčín",
      "Havlíčkův Brod",
      "Jablonec nad Nisou",
      "Jihlava",
      "Královéhradecký kraj",
      "Blansko",
      "Louny",
      "Kolín",
      "Praha-západ",
      "Beroun",
      "Teplice",
      "Vyškov",
      "Opava",
      "Jindřichův Hradec",
      "Jeseník",
      "Přerov",
      "Benešov",
      "Strakonice",
      "Most",
      "Znojmo",
      "Kladno",
      "Česká Lípa",
      "Chrudim",
      "Rychnov nad Kněžnou",
      "Mělník",
      "Jihočeský kraj",
      "Jičín",
      "Domažlice",
      "Šumperk",
      "Mladá Boleslav",
      "Bruntál",
      "Pelhřimov",
      "Tachov",
      "Ústí nad Orlicí",
      "Žďár nad Sázavou",
      "Kutná Hora",
    ],
  },
  {
    "name": "Congo",
    "flag": "cd.png",
    "code": "243",
    "states": [
      "Tshuapa",
      "Tanganyika",
      "Haut-Uélé",
      "Kasaï Oriental",
      "Sud-Kivu",
      "Nord-Ubangi",
      "Kwango",
      "Kinshasa",
      "Kasaï Central",
      "Sankuru",
      "Équateur",
      "Maniema",
      "Kongo Central",
      "Lomami",
      "Sud-Ubangi",
      "Nord-Kivu",
      "Haut-Katanga",
      "Ituri",
      "Mongala",
      "Bas-Uélé",
      "Mai-Ndombe",
      "Tshopo",
      "Kasaï",
      "Haut-Lomami",
      "Kwilu",
      "Lualaba",
    ]
  },
  {
    "name": "Denmark",
    "flag": "dk.png",
    "code": "45",
    "states": [
      "Region Zealand",
      "Region of Southern Denmark",
      "Capital Region of Denmark",
      "Central Denmark Region",
      "North Denmark Region",
    ]
  },
  {
    "name": "Djibouti",
    "flag": "dj.png",
    "code": "253",
    "states": [
      "Obock Region",
      "Djibouti",
      "Dikhil Region",
      "Tadjourah Region",
      "Arta Region",
      "Ali Sabieh Region",
    ]
  },
  {
    "name": "East Timor",
    "flag": "tl.png",
    "code": "670",
    "states": [
      "Viqueque",
      "Liquiçá",
      "Ermera District",
      "Manatuto District",
      "Ainaro",
      "Manufahi",
      "Aileu",
      "Baucau",
      "Cova Lima",
      "Lautém",
      "Dili",
      "Bobonaro",
    ],
  },
  {
    "name": "Ecuador",
    "flag": "ec.png",
    "code": "593",
    "states": [
      "Galápagos",
      "Sucumbíos",
      "Pastaza",
      "Tungurahua",
      "Zamora Chinchipe",
      "Los Ríos",
      "Imbabura",
      "Santa Elena",
      "Manabí",
      "Guayas",
      "Carchi",
      "Napo",
      "Cañar",
      "Morona-Santiago",
      "Santo Domingo de los Tsáchilas",
      "Bolívar",
      "Cotopaxi",
      "Esmeraldas",
      "Azuay",
      "El Oro",
      "Chimborazo",
      "Orellana",
      "Pichincha",
      "Loja",
    ]
  },
  {
    "name": "Egypt",
    "flag": "eg.png",
    "code": "20",
    "states": [
      "Kafr el-Sheikh",
      "Cairo",
      "Damietta",
      "Aswan",
      "Sohag",
      "North Sinai",
      "Monufia",
      "Port Said",
      "Beni Suef",
      "Matrouh",
      "Qalyubia",
      "Suez",
      "Gharbia",
      "Alexandria",
      "Asyut",
      "South Sinai",
      "Faiyum",
      "Giza",
      "Red Sea",
      "Beheira",
      "Luxor",
      "Minya",
      "Ismailia",
      "Dakahlia",
      "New Valley",
      "Qena",
      "Sharqia",
    ]
  },
  {
    "name": "Equatorial Guinea",
    "flag": "gq.png",
    "code": "240",
    "states": [
      "Río Muni",
      "Kié-Ntem Province",
      "Wele-Nzas Province",
      "Litoral Province",
      "Insular Region",
      "Bioko Sur Province",
      "Annobón Province",
      "Centro Sur Province",
      "Bioko Norte Province",
    ]
  },
  {
    "name": "Eritrea",
    "flag": "er.png",
    "code": "291",
    "states": [
      "Northern Red Sea Region",
      "Anseba Region",
      "Maekel Region",
      "Debub Region",
      "Gash-Barka Region",
      "Southern Red Sea Region",
    ]
  },
  {
    "name": "Estonia",
    "flag": "ee.png",
    "code": "372",
    "states": [
      "Hiiu",
      "Viljandi",
      "Tartu",
      "Valga",
      "Rapla",
      "Võru",
      "Saare",
      "Pärnu",
      "Põlva",
      "Lääne-Viru",
      "Jõgeva",
      "Järva",
      "Harju",
      "Lääne",
      "Ida-Viru",
    ]
  },
  {
    "name": "Ethiopia",
    "flag": "et.png",
    "code": "251",
    "states": [
      "Southwestern Ethiopia",
      "Somali Region",
      "Amhara Region",
      "Tigray Region",
      "Oromia Region",
      "Afar Region",
      "Harari Region",
      "Dire Dawa",
      "Benishangul-Gumuz Region",
      "Gambela Region",
      "Addis Ababa",
    ]
  },
  {
    "name": "Fiji",
    "flag": "fj.png",
    "code": "679",
    "states": [
      "Lomaiviti",
      "Ba",
      "Tailevu",
      "Nadroga-Navosa",
      "Rewa",
      "Northern Division",
      "Macuata",
      "Western Division",
      "Cakaudrove",
      "Serua",
      "Ra",
      "Naitasiri",
      "Namosi",
      "Central Division",
      "Bua",
      "Rotuma",
      "Eastern Division",
      "Lau",
      "Kadavu",
    ]
  },
  {
    "name": "Finland",
    "flag": "fi.png",
    "code": "358",
    "states": [
      "Tavastia Proper",
      "Central Ostrobothnia",
      "Southern Savonia",
      "Kainuu",
      "South Karelia",
      "Southern Ostrobothnia",
      "Lapland",
      "Satakunta",
      "Päijänne Tavastia",
      "Northern Savonia",
      "North Karelia",
      "Northern Ostrobothnia",
      "Pirkanmaa",
      "Finland Proper",
      "Ostrobothnia",
      "Åland Islands",
      "Uusimaa",
      "Central Finland",
      "Kymenlaakso",
    ]
  },
  {
    "name": "France",
    "flag": "fr.png",
    "code": "33",
    "states": [
      "Saint-Barthélemy",
      "Nouvelle-Aquitaine",
      "Île-de-France",
      "Mayotte",
      "Auvergne-Rhône-Alpes",
      "Occitanie",
      "Pays-de-la-Loire",
      "Normandie",
      "Corse",
      "Bretagne",
      "Saint-Martin",
      "Wallis and Futuna",
      "Alsace",
      "Provence-Alpes-Côte-d’Azur",
      "Paris",
      "Centre-Val de Loire",
      "Grand-Est",
      "Saint Pierre and Miquelon",
      "French Guiana",
      "La Réunion",
      "French Polynesia",
      "Bourgogne-Franche-Comté",
      "Martinique",
      "Hauts-de-France",
      "Guadeloupe",
      "Ain",
      "Aisne",
      "Allier",
      "Alpes-de-Haute-Provence",
      "Hautes-Alpes",
      "Alpes-Maritimes",
      "Ardèche",
      "Ardennes",
      "Ariège",
      "Aube",
      "Aude",
      "Aveyron",
      "Bouches-du-Rhône",
      "Calvados",
      "Cantal",
      "Charente",
      "Charente-Maritime",
      "Cher",
      "Corrèze",
      "Côte-d'Or",
      "Côtes-d'Armor",
      "Creuse",
      "Dordogne",
      "Doubs",
      "Drôme",
      "Eure",
      "Eure-et-Loir",
      "Finistère",
      "Corse-du-Sud",
      "Haute-Corse",
      "Gard",
      "Haute-Garonne",
      "Gers",
      "Gironde",
      "Hérault",
      "Ille-et-Vilaine",
      "Indre",
      "Indre-et-Loire",
      "Isère",
      "Jura",
      "Landes",
      "Loir-et-Cher",
      "Loire",
      "Haute-Loire",
      "Loire-Atlantique",
      "Loiret",
      "Lot",
      "Lot-et-Garonne",
      "Lozère",
      "Maine-et-Loire",
      "Manche",
      "Marne",
      "Haute-Marne",
      "Mayenne",
      "Meurthe-et-Moselle",
      "Meuse",
      "Morbihan",
      "Moselle",
      "Nièvre",
      "Nord",
      "Oise",
      "Orne",
      "Pas-de-Calais",
      "Puy-de-Dôme",
      "Pyrénées-Atlantiques",
      "Hautes-Pyrénées",
      "Pyrénées-Orientales",
      "Bas-Rhin",
      "Haut-Rhin",
      "Rhône",
      "Métropole de Lyon",
      "Haute-Saône",
      "Saône-et-Loire",
      "Sarthe",
      "Savoie",
      "Haute-Savoie",
      "Seine-Maritime",
      "Seine-et-Marne",
      "Yvelines",
      "Deux-Sèvres",
      "Somme",
      "Tarn",
      "Tarn-et-Garonne",
      "Var",
      "Vaucluse",
      "Vendée",
      "Vienne",
      "Haute-Vienne",
      "Vosges",
      "Yonne",
      "Territoire de Belfort",
      "Essonne",
      "Hauts-de-Seine",
      "Seine-Saint-Denis",
      "Val-de-Marne",
      "Val-d'Oise",
      "Clipperton",
      "French Southern and Antarctic Lands",
    ],
  },
  {
    "name": "Gabon",
    "flag": "ga.png",
    "code": "241",
    "states": [
      "Woleu-Ntem Province",
      "Ogooué-Ivindo Province",
      "Nyanga Province",
      "Haut-Ogooué Province",
      "Estuaire Province",
      "Ogooué-Maritime Province",
      "Ogooué-Lolo Province",
      "Moyen-Ogooué Province",
      "Ngounié Province",
    ]
  },
  {
    "name": "Gambia",
    "flag": "gm.png",
    "code": "220",
    "states": [
      "Banjul",
      "West Coast Division",
      "Upper River Division",
      "Central River Division",
      "Lower River Division",
      "North Bank Division",
    ]
  },
  {
    "name": "Georgia",
    "flag": "ge.png",
    "code": "995",
    "states": [
      "Khelvachauri",
      "Senaki",
      "Tbilisi",
      "Adjara",
      "Autonomous Republic of Abkhazia",
      "Mtskheta-Mtianeti",
      "Shida Kartli",
      "Kvemo Kartli",
      "Imereti",
      "Samtskhe-Javakheti",
      "Guria",
      "Samegrelo-Zemo Svaneti",
      "Racha-Lechkhumi and Kvemo Svaneti",
      "Kakheti",
    ]
  },
  {
    "name": "Germany",
    "flag": "de.png",
    "code": "49",
    "states": [
      "Schleswig-Holstein",
      "Baden-Württemberg",
      "Mecklenburg-Vorpommern",
      "Lower Saxony",
      "Bavaria",
      "Berlin",
      "Saxony-Anhalt",
      "Brandenburg",
      "Bremen",
      "Thuringia",
      "Hamburg",
      "North Rhine-Westphalia",
      "Hesse",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
    ]
  },
  {
    "name": "Ghana",
    "flag": "gh.png",
    "code": "233",
    "states": [
      "Ashanti",
      "Western",
      "Eastern",
      "Northern",
      "Central",
      "Ahafo",
      "Greater Accra",
      "Upper East",
      "Volta",
      "Upper West",
      "Bono East",
      "Bono",
      "North East",
      "Oti",
      "Savannah",
      "Western North",
    ],
  },
  {
    "name": "Greece",
    "flag": "gr.png",
    "code": "30",
    "states": [
      "Karditsa Regional Unit",
      "West Greece Region",
      "Thessaloniki Regional Unit",
      "Arcadia Prefecture",
      "Imathia Regional Unit",
      "Kastoria Regional Unit",
      "Euboea",
      "Grevena Prefecture",
      "Preveza Prefecture",
      "Lefkada Regional Unit",
      "Argolis Regional Unit",
      "Laconia",
      "Pella Regional Unit",
      "West Macedonia Region",
      "Crete Region",
      "Epirus Region",
      "Kilkis Regional Unit",
      "Kozani Prefecture",
      "Ioannina Regional Unit",
      "Phthiotis Prefecture",
      "Chania Regional Unit",
      "Achaea Regional Unit",
      "East Macedonia and Thrace",
      "South Aegean",
      "Peloponnese Region",
      "East Attica Regional Unit",
      "Serres Prefecture",
      "Attica Region",
      "Aetolia-Acarnania Regional Unit",
      "Corfu Prefecture",
      "Central Macedonia",
      "Boeotia Regional Unit",
      "Kefalonia Prefecture",
      "Central Greece Region",
      "Corinthia Regional Unit",
      "Drama Regional Unit",
      "Ionian Islands Region",
      "Larissa Prefecture",
    ],
  },
  {
    "name": "Guatemala",
    "flag": "gt.png",
    "code": "502",
    "states": [
      "Quiché Department",
      "Jalapa Department",
      "Izabal Department",
      "Suchitepéquez Department",
      "Sololá Department",
      "El Progreso Department",
      "Totonicapán Department",
      "Retalhuleu Department",
      "Santa Rosa Department",
      "Chiquimula Department",
      "San Marcos Department",
      "Quetzaltenango Department",
      "Petén Department",
      "Huehuetenango Department",
      "Alta Verapaz Department",
      "Guatemala Department",
      "Jutiapa Department",
      "Baja Verapaz Department",
      "Chimaltenango Department",
      "Sacatepéquez Department",
      "Escuintla Department",
    ],
  },
  {
    "name": "Honduras",
    "flag": "hn.png",
    "code": "504",
    "states": [
      "Choluteca Department",
      "Comayagua Department",
      "El Paraíso Department",
      "Intibucá Department",
      "Bay Islands Department",
      "Cortés Department",
      "Atlántida Department",
      "Gracias a Dios Department",
      "Copán Department",
      "Olancho Department",
      "Colón Department",
      "Francisco Morazán Department",
      "Santa Bárbara Department",
      "Lempira Department",
      "Valle Department",
      "Ocotepeque Department",
      "Yoro Department",
      "La Paz Department",
    ],
  },
  {
    "name": "Hong Kong",
    "flag": "hk.png",
    "code": "852",
    "states": [
      "Yuen Long District",
      "Tsuen Wan District",
      "Sai Kung District",
      "Islands District",
      "Central & Western District",
      "Wan Chai",
      "Eastern",
      "Southern",
      "Yau Tsim Mong",
      "Sham Shui Po",
      "Kowloon City",
      "Wong Tai Sin",
      "Kwun Tong",
      "Kwai Tsing",
      "Tuen Mun",
      "North",
      "Sha Tin",
    ],
  },
  {
    "name": "Hungary",
    "flag": "hu.png",
    "code": "36",
    "states": [
      "Hódmezővásárhely",
      "Érd",
      "Szeged",
      "Nagykanizsa",
      "Csongrád",
      "Debrecen",
      "Székesfehérvár",
      "Nyíregyháza",
      "Somogy",
      "Békéscsaba",
      "Eger",
      "Tolna",
      "Vas",
      "Heves",
      "Győr",
      "Győr-Moson-Sopron",
      "Jász-Nagykun-Szolnok",
      "Fejér",
      "Szabolcs-Szatmár-Bereg",
      "Zala",
      "Szolnok",
      "Bács-Kiskun",
      "Dunaújváros",
      "Zalaegerszeg",
      "Nógrád",
      "Szombathely",
      "Pécs",
      "Veszprém",
      "Baranya",
      "Kecskemét",
      "Sopron",
      "Borsod-Abaúj-Zemplén",
      "Pest",
      "Békés",
      "Szekszárd",
      "Veszprém",
      "Hajdú-Bihar",
      "Budapest",
      "Miskolc",
      "Tatabánya",
      "Kaposvár",
      "Salgótarján",
      "Komárom-Esztergom",
    ],
  },
  {
    "name": "Iceland",
    "flag": "is.png",
    "code": "354",
    "states": [
      "Southern Peninsula Region",
      "Capital Region",
      "Westfjords",
      "Eastern Region",
      "Southern Region",
      "Northwestern Region",
      "Western Region",
      "Northeastern Region",
    ],
  },
  {
    "name": "India",
    "flag": "in.png",
    "code": "91",
    "states": [
      "Meghalaya",
      "Haryana",
      "Maharashtra",
      "Goa",
      "Manipur",
      "Puducherry",
      "Telangana",
      "Odisha",
      "Rajasthan",
      "Punjab",
      "Uttarakhand",
      "Andhra Pradesh",
      "Nagaland",
      "Lakshadweep",
      "Himachal Pradesh",
      "Delhi",
      "Uttar Pradesh",
      "Andaman and Nicobar Islands",
      "Arunachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Assam",
      "Kerala",
      "Jammu and Kashmir",
      "Gujarat",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Sikkim",
      "Tamil Nadu",
      "Mizoram",
      "Bihar",
      "Tripura",
      "Madhya Pradesh",
      "Chhattisgarh",
      "Ladakh",
      "West Bengal",
    ],
  },
  {
    "name": "Indonesia",
    "flag": "id.png",
    "code": "62",
    "states": [
      "Sumatera Utara",
      "Bengkulu",
      "Kalimantan Tengah",
      "Sulawesi Selatan",
      "Sulawesi Tenggara",
      "Papua",
      "Papua Barat",
      "Maluku",
      "Maluku Utara",
      "Jawa Tengah",
      "Kalimantan Timur",
      "DKI Jakarta",
      "Kalimantan Barat",
      "Kepulauan Riau",
      "Sulawesi Utara",
      "Riau",
      "Banten",
      "Lampung",
      "Gorontalo",
      "Sulawesi Tengah",
      "Nusa Tenggara Barat",
      "Jambi",
      "Sumatera Selatan",
      "Sulawesi Barat",
      "Nusa Tenggara Timur",
      "Kalimantan Selatan",
      "Kepulauan Bangka Belitung",
      "Aceh",
      "Kalimantan Utara",
      "Jawa Barat",
      "Bali",
      "Jawa Timur",
      "Sumatera Barat",
      "DI Yogyakarta",
    ]
  },
  {
    "name": "Iran",
    "flag": "ir.png",
    "code": "98",
    "states": [
      "Markazi",
      "Khuzestan",
      "Ilam",
      "Kermanshah",
      "Gilan",
      "Chaharmahal & Bakhtiari",
      "Qom",
      "Isfahan",
      "West Azarbaijan",
      "Zanjan",
      "Kohgiluyeh & Boyer-Ahmad",
      "Razavi Khorasan",
      "Lorestan",
      "Alborz",
      "South Khorasan",
      "Sistan & Baluchestan",
      "Bushehr",
      "Golestan",
      "Ardabil",
      "Kurdistan",
      "Yazd",
      "Hormozgan",
      "Mazandaran",
      "Fars",
      "Semnan",
      "Qazvin",
      "North Khorasan",
      "Kerman",
      "East Azerbaijan",
      "Tehran",
      "Hamadan",
    ]
  },
  {
    "name": "Iraq",
    "flag": "iq.png",
    "code": "964",
    "states": [
      "Dhi Qar",
      "Babylon",
      "Al-Qādisiyyah",
      "Karbala",
      "Al Muthanna",
      "Baghdad",
      "Basra",
      "Saladin",
      "Najaf",
      "Nineveh",
      "Al Anbar",
      "Diyala",
      "Maysan",
      "Dohuk",
      "Erbil",
      "Sulaymaniyah",
      "Wasit",
      "Kirkuk",
    ]
  },
  {
    "name": "Ireland",
    "flag": "ie.png",
    "code": "353",
    "states": [
      "Tipperary",
      "Sligo",
      "Donegal",
      "Dublin",
      "Leinster",
      "Cork",
      "Monaghan",
      "Longford",
      "Kerry",
      "Offaly",
      "Galway",
      "Munster",
      "Roscommon",
      "Kildare",
      "Louth",
      "Mayo",
      "Wicklow",
      "Ulster",
      "Connacht",
      "Cavan",
      "Waterford",
      "Kilkenny",
      "Clare",
      "Meath",
      "Wexford",
      "Limerick",
      "Carlow",
      "Laois",
      "Westmeath",
    ],
  },
  {
    "name": "Israel",
    "flag": "il.png",
    "code": "972",
    "states": [
      "Northern District",
      "Central District",
      "Southern District",
      "Haifa District",
      "Jerusalem District",
      "Tel Aviv District",
    ],
  },
  {
    "name": "Italy",
    "flag": "it.png",
    "code": "39",
    "states": [
      "Tuscany",
      "Padua",
      "Parma",
      "Siracusa",
      "Palermo",
      "Campania",
      "Marche",
      "Reggio Calabria",
      "Ancona",
      "Venice",
      "Latina",
      "Lecce",
      "Pavia",
      "Lecco",
      "Lazio",
      "Abruzzo",
      "Florence",
      "Ascoli Piceno",
      "Cagliari",
      "Umbria",
      "Bologna",
      "Pisa",
      "Barletta-Andria-Trani",
      "Pistoia",
      "Apulia",
      "Belluno",
      "Pordenone",
      "Perugia",
      "Avellino",
      "Pesaro and Urbino",
      "Pescara",
      "Molise",
      "Piacenza",
      "Potenza",
      "Milan",
      "Genoa",
      "Prato",
      "Benevento",
      "Piedmont",
      "Calabria",
      "Bergamo",
      "Lombardy",
      "Basilicata",
      "Ravenna",
      "Reggio Emilia",
      "Sicily",
      "Turin",
      "Rome",
      "Rieti",
      "Rimini",
      "Brindisi",
      "Sardinia",
      "Aosta Valley",
      "Brescia",
      "Caltanissetta",
      "Rovigo",
      "Salerno",
      "Campobasso",
      "Sassari",
      "Enna",
      "Naples",
      "Trentino-South Tyrol",
      "Verbano-Cusio-Ossola",
      "Agrigento",
      "Catanzaro",
      "Ragusa",
      "South Sardinia",
      "Caserta",
      "Savona",
      "Trapani",
      "Siena",
      "Viterbo",
      "Verona",
      "Vibo Valentia",
      "Vicenza",
      "Chieti",
      "Como",
      "Sondrio",
      "Cosenza",
      "Taranto",
      "Fermo",
      "Livorno",
      "Ferrara",
      "Lodi",
      "Trentino",
      "Lucca",
      "Macerata",
      "Cremona",
      "Teramo",
      "Veneto",
      "Crotone",
      "Terni",
      "Friuli–Venezia Giulia",
      "Modena",
      "Mantua",
      "Massa and Carrara",
      "Matera",
      "Medio Campidano",
      "Treviso",
      "Trieste",
      "Udine",
      "Varese",
      "Catania",
      "South Tyrol",
      "Liguria",
      "Monza and Brianza",
      "Messina",
      "Foggia",
      "Bari",
      "Emilia-Romagna",
      "Novara",
      "Cuneo",
      "Frosinone",
      "Gorizia",
      "Biella",
      "Forlì-Cesena",
      "Asti",
      "L'Aquila",
      "Alessandria",
      "Vercelli",
      "Oristano",
      "Grosseto",
      "Imperia",
      "Isernia",
      "Nuoro",
      "La Spezia",
    ]
  },
  {
    "name": "Ivory Coast",
    "flag": "ci.png",
    "code": "225",
    "states": [
      "Savanes Region",
      "Agnéby",
      "Lagunes District",
      "Sud-Bandama",
      "Montagnes District",
      "Moyen-Comoé",
      "Marahoué Region",
      "Lacs District",
      "Fromager",
      "Abidjan",
      "Bas-Sassandra Region",
      "Bafing Region",
      "Vallée du Bandama District",
      "Haut-Sassandra",
      "Lagunes region",
      "Lacs Region",
      "Zanzan Region",
      "Denguélé Region",
      "Bas-Sassandra District",
      "Denguélé District",
      "Dix-Huit Montagnes",
      "Moyen-Cavally",
      "Vallée du Bandama Region",
      "Sassandra-Marahoué District",
      "Worodougou",
      "Woroba District",
      "Gôh-Djiboua District",
      "Sud-Comoé",
      "Yamoussoukro",
      "Comoé District",
      "N'zi-Comoé",
    ],
  },
  {
    "name": "Japan",
    "flag": "jp.png",
    "code": "81",
    "states": [
      "Okayama Prefecture",
      "Chiba Prefecture",
      "Ōita Prefecture",
      "Tokyo",
      "Nara Prefecture",
      "Shizuoka Prefecture",
      "Shimane Prefecture",
      "Aichi Prefecture",
      "Hiroshima Prefecture",
      "Akita Prefecture",
      "Ishikawa Prefecture",
      "Hyōgo Prefecture",
      "Hokkaidō Prefecture",
      "Mie Prefecture",
      "Kyōto Prefecture",
      "Yamaguchi Prefecture",
      "Tokushima Prefecture",
      "Yamagata Prefecture",
      "Toyama Prefecture",
      "Aomori Prefecture",
      "Kagoshima Prefecture",
      "Niigata Prefecture",
      "Kanagawa Prefecture",
      "Nagano Prefecture",
      "Wakayama Prefecture",
      "Shiga Prefecture",
      "Kumamoto Prefecture",
      "Fukushima Prefecture",
      "Fukui Prefecture",
      "Nagasaki Prefecture",
      "Tottori Prefecture",
      "Ibaraki Prefecture",
      "Yamanashi Prefecture",
      "Okinawa Prefecture",
      "Tochigi Prefecture",
      "Miyazaki Prefecture",
      "Iwate Prefecture",
      "Miyagi Prefecture",
      "Gifu Prefecture",
      "Ōsaka Prefecture",
      "Saitama Prefecture",
      "Fukuoka Prefecture",
      "Gunma Prefecture",
      "Saga Prefecture",
      "Kagawa Prefecture",
      "Ehime Prefecture",
      "Kōchi Prefecture",
    ],
  },
  {
    "name": "Jordan",
    "flag": "jo.png",
    "code": "962",
    "states": [
      "Karak",
      "Tafilah",
      "Madaba",
      "Aqaba",
      "Irbid",
      "Balqa",
      "Mafraq",
      "Ajloun",
      "Ma'an",
      "Amman",
      "Jerash",
      "Zarqa",
    ]
  },
  {
    "name": "Kazakhstan",
    "flag": "kz.png",
    "code": "7",
    "states": [
      "Mangystau Region",
      "Kyzylorda Region",
      "Almaty Region",
      "North Kazakhstan Region",
      "Akmola Region",
      "Pavlodar Region",
      "Jambyl Region",
      "West Kazakhstan Province",
      "Turkestan Region",
      "Karaganda Region",
      "Aktobe Region",
      "Almaty",
      "Atyrau Region",
      "East Kazakhstan Region",
      "Baikonur",
      "Nur-Sultan",
      "Kostanay Region",
    ]
  },
  {
    "name": "Kenya",
    "flag": "ke.png",
    "code": "254",
    "states": [
      "Kakamega",
      "Kisii",
      "Busia",
      "Embu",
      "Laikipia",
      "Nandi",
      "Lamu",
      "Kirinyaga",
      "Bungoma",
      "Uasin Gishu",
      "Isiolo",
      "Kisumu",
      "Kwale",
      "Kilifi",
      "Narok",
      "Taita–Taveta",
      "Murang'a",
      "Nyeri",
      "Baringo",
      "Wajir",
      "Trans Nzoia",
      "Machakos",
      "Tharaka-Nithi",
      "Siaya",
      "Mandera",
      "Makueni",
      "Migori",
      "Nairobi City",
      "Nyandarua",
      "Kericho",
      "Marsabit",
      "Homa Bay",
      "Garissa",
      "Kajiado",
      "Meru",
      "Kiambu",
      "Mombasa",
      "Elgeyo-Marakwet",
      "Vihiga",
      "Nakuru",
      "Tana River",
      "Turkana",
      "Samburu",
      "West Pokot",
      "Nyamira",
      "Bomet",
      "Kitui",
    ]
  },
  {
    "name": "Kosova",
    "flag": "xk.png",
    "code": "383",
    "states": [
      "Prizren District",
      "Peć District",
      "Uroševac (Ferizaj)",
      "Đakovica (Gjakove)",
      "Gjilan District",
      "Kosovska Mitrovica District",
      "Pristina (Priştine)",
    ]
  },
  {
    "name": "Kuwait",
    "flag": "kw.png",
    "code": "965",
    "states": [
      "Al Jahra",
      "Hawalli",
      "Mubarak Al-Kabeer",
      "Al Farwaniyah",
      "Capital",
      "Al Ahmadi",
    ]
  },
  {
    "name": "Kyrgyzstan",
    "flag": "kg.png",
    "code": "996",
    "states": [
      "Talas Region",
      "Batken Region",
      "Naryn Region",
      "Jalal-Abad Region",
      "Bishkek",
      "Issyk-Kul Region",
      "Osh",
      "Chuy Region",
      "Osh Region",
    ]
  },
  {
    "name": "Loas",
    "flag": "la.png",
    "code": "856",
    "states": [
      "Luang Prabang Province",
      "Vientiane Prefecture",
      "Vientiane Province",
      "Salavan Province",
      "Attapeu Province",
      "Xaisomboun Province",
      "Sekong Province",
      "Bolikhamsai Province",
      "Khammouane Province",
      "Phongsaly Province",
      "Oudomxay Province",
      "Houaphanh Province",
      "Savannakhet Province",
      "Bokeo Province",
      "Luang Namtha Province",
      "Sainyabuli Province",
      "Xaisomboun",
      "Xiangkhouang Province",
      "Champasak Province",
    ]
  },
  {
    "name": "Latvia",
    "flag": "lv.png",
    "code": "371",
    "states": [
      "Salacgrīva",
      "Vecumnieki",
      "Naukšēni",
      "Ilūkste",
      "Gulbene",
      "Līvāni",
      "Salaspils",
      "Ventspils",
      "Rundāle",
      "Pļaviņas",
      "Vārkava",
      "Jaunpiebalga",
      "Sēja",
      "Tukums",
      "Cibla",
      "Burtnieki",
      "Ķegums",
      "Krustpils",
      "Cesvaine",
      "Skrīveri",
      "Ogre",
      "Olaine",
      "Limbaži",
      "Lubāna",
      "Kandava",
      "Ventspils",
      "Krimulda",
      "Rugāji",
      "Jelgava",
      "Valka",
      "Rūjiena",
      "Babīte",
      "Dundaga",
      "Priekule",
      "Zilupe",
      "Varakļāni",
      "Nereta",
      "Madona",
      "Sala",
      "Ķekava",
      "Nīca",
      "Dobele",
      "Jēkabpils",
      "Saldus",
      "Roja",
      "Iecava",
      "Ozolnieki",
      "Saulkrasti",
      "Ērgļi",
      "Aglona",
      "Jūrmala",
      "Skrunda",
      "Engure",
      "Inčukalns",
      "Mārupe",
      "Mērsrags",
      "Koknese",
      "Kārsava",
      "Carnikava",
      "Rēzekne",
      "Viesīte",
      "Ape",
      "Durbe",
      "Talsi",
      "Liepāja",
      "Mālpils",
      "Smiltene",
      "Daugavpils",
      "Jēkabpils",
      "Bauska",
      "Vecpiebalga",
      "Pāvilosta",
      "Brocēni",
      "Cēsis",
      "Grobiņa",
      "Beverīna",
      "Aizkraukle",
      "Valmiera",
      "Krāslava",
      "Jaunjelgava",
      "Sigulda",
      "Viļaka",
      "Stopiņi",
      "Rauna",
      "Tērvete",
      "Auce",
      "Baldone",
      "Preiļi",
      "Aloja",
      "Alsunga",
      "Viļāni",
      "Alūksne",
      "Līgatne",
      "Jaunpils",
      "Kuldīga",
      "Riga",
      "Daugavpils",
      "Ropaži",
      "Strenči",
      "Kocēni",
      "Aizpute",
      "Amata",
      "Baltinava",
      "Aknīste",
      "Jelgava",
      "Ludza",
      "Riebiņi",
      "Rucava",
      "Dagda",
      "Balvi",
      "Priekuļi",
      "Pārgauja",
      "Vaiņode",
      "Rēzekne",
      "Garkalne",
      "Ikšķile",
      "Lielvārde",
      "Mazsalaca",
    ],
  },
  {
    "name": "Lebanon",
    "flag": "lb.png",
    "code": "961",
    "states": [
      "South",
      "Mount Lebanon",
      "Baalbek-Hermel",
      "North",
      "Akkar",
      "Beirut",
      "Beqaa",
      "Nabatieh",
    ],
  },
  {
    "name": "Lesotho",
    "flag": "ls.png",
    "code": "266",
    "states": [
      "Mafeteng District",
      "Mohale's Hoek District",
      "Mokhotlong District",
      "Qacha's Nek District",
      "Leribe District",
      "Quthing District",
      "Maseru District",
      "Butha-Buthe District",
      "Berea District",
      "Thaba-Tseka District",
    ]
  },
  {
    "name": "Liberia",
    "flag": "lr.png",
    "code": "231",
    "states": [
      "Montserrado",
      "River Cess",
      "Bong",
      "Sinoe",
      "Grand Cape Mount",
      "Lofa",
      "River Gee",
      "Grand Gedeh",
      "Grand Bassa",
      "Bomi",
      "Maryland",
      "Margibi",
      "Gbarpolu",
      "Grand Kru",
      "Nimba",
    ]
  },
  {
    "name": "Libya",
    "flag": "ly.png",
    "code": "218",
    "states": [
      "Murqub",
      "Nuqat al Khams",
      "Zawiya District",
      "Al Wahat District",
      "Sabha District",
      "Derna District",
      "Murzuq District",
      "Marj District",
      "Ghat District",
      "Jufra",
      "Tripoli District",
      "Kufra District",
      "Wadi al Hayaa District",
      "Jabal al Gharbi District",
      "Wadi al Shatii District",
      "Nalut District",
      "Sirte District",
      "Misrata District",
      "Jafara",
      "Jabal al Akhdar",
      "Benghazi",
    ]
  },
  {
    "name": "Liechtenstein",
    "flag": "li.png",
    "code": "423",
    "states": [
      "Schellenberg",
      "Schaan",
      "Eschen",
      "Vaduz",
      "Ruggell",
      "Planken",
      "Mauren",
      "Triesenberg",
      "Gamprin",
      "Balzers",
      "Triesen",
    ],
  },
  {
    "name": "Lithuania",
    "flag": "lt.png",
    "code": "370",
    "states": [
      "Plungė District",
      "Šiauliai District",
      "Jurbarkas District",
      "Kaunas",
      "Mažeikiai District",
      "Panevėžys",
      "Elektrėnai",
      "Švenčionys District",
      "Akmenė District",
      "Ignalina District",
      "Neringa",
      "Visaginas",
      "Kaunas District",
      "Biržai District",
      "Jonava District",
      "Radviliškis District",
      "Telšiai",
      "Marijampolė",
      "Kretinga District",
      "Tauragė District",
      "Tauragė",
      "Alytus",
      "Kazlų Rūda",
      "Šakiai District",
      "Šalčininkai District",
      "Prienai District",
      "Druskininkai",
      "Kaunas City",
      "Joniškis District",
      "Molėtai District",
      "Kaišiadorys District",
      "Kėdainiai District",
      "Kupiškis District",
      "Šiauliai",
      "Raseiniai District",
      "Palanga City",
      "Panevėžys City",
      "Rietavas",
      "Kalvarija",
      "Vilnius District",
      "Trakai District",
      "Širvintos District",
      "Pakruojis District",
      "Ukmergė District",
      "Klaipeda City",
      "Utena District",
      "Alytus District",
      "Klaipėda",
      "Vilnius",
      "Varėna District",
      "Birštonas",
      "Klaipėda District",
      "Alytus City",
      "Vilnius City",
      "Šilutė District",
      "Telšiai District",
      "Šiauliai City",
      "Marijampolė",
      "Lazdijai District",
      "Pagėgiai",
      "Šilalė District",
      "Panevėžys District",
      "Rokiškis District",
      "Pasvalys District",
      "Skuodas District",
      "Kelmė District",
      "Zarasai District",
      "Vilkaviškis District",
      "Utena",
    ],
  },
  {
    "name": "Luxembourg",
    "flag": "lu.png",
    "code": "352",
    "states": [
      "Canton of Diekirch",
      "Luxembourg District",
      "Canton of Echternach",
      "Canton of Redange",
      "Canton of Esch-sur-Alzette",
      "Canton of Capellen",
      "Canton of Remich",
      "Grevenmacher District",
      "Canton of Clervaux",
      "Canton of Mersch",
      "Canton of Vianden",
      "Diekirch District",
      "Canton of Grevenmacher",
      "Canton of Wiltz",
      "Canton of Luxembourg",
    ],
  },
  {
    "name": "Macedonia",
    "flag": "mk.png",
    "code": "389",
    "states": [
      "SvetiNikole",
      "Kratovo",
      "Zajas",
      "StaroNagoričane",
      "Češinovo-Obleševo",
      "Debarca",
      "Probištip",
      "Krivogaštani",
      "Gevgelija",
      "Bogdanci",
      "Vraneštica",
      "Veles",
      "Bosilovo",
      "Mogila",
      "Tearce",
      "DemirKapija",
      "Aračinovo",
      "Drugovo",
      "Vasilevo",
      "Lipkovo",
      "Brvenica",
      "Štip",
      "Vevčani",
      "Tetovo",
      "Negotino",
      "Konče",
      "Prilep",
      "Saraj",
      "Želino",
      "MavrovoandRostuša",
      "Plasnica",
      "Valandovo",
      "Vinica",
      "Zrnovci",
      "Karbinci",
      "Dolneni",
      "Čaška",
      "KrivaPalanka",
      "Jegunovce",
      "Bitola",
      "ŠutoOrizari",
      "Karpoš",
      "Oslomej",
      "Kumanovo",
      "GreaterSkopje",
      "Pehčevo",
      "KiselaVoda",
      "DemirHisar",
      "Kičevo",
      "Vrapčište",
      "Ilinden",
      "Rosoman",
      "MakedonskiBrod",
      "Gostivar",
      "Butel",
      "Delčevo",
      "Novaci",
      "Dojran",
      "Petrovec",
      "Ohrid",
      "Struga",
      "MakedonskaKamenica",
      "Centar",
      "Aerodrom",
      "Čair",
      "Lozovo",
      "Zelenikovo",
      "GaziBaba",
      "Gradsko",
      "Radoviš",
      "Strumica",
      "Studeničani",
      "Resen",
      "Kavadarci",
      "Kruševo",
      "Čučer-Sandevo",
      "Berovo",
      "Rankovce",
      "NovoSelo",
      "Sopište",
      "CentarŽupa",
      "Bogovinje",
      "GjorčePetrov",
      "Kočani",
    ],
  },
  {
    "name": "Madagascar",
    "flag": "mg.png",
    "code": "261",
    "states": [
      "Fianarantsoa Province",
      "Toliara Province",
      "Antsiranana Province",
      "Antananarivo Province",
      "Toamasina Province",
      "Mahajanga Province",
    ]
  },
  {
    "name": "Malawi",
    "flag": "mw.png",
    "code": "265",
    "states": [
      "Machinga District",
      "Zomba District",
      "Mwanza District",
      "Nsanje District",
      "Salima District",
      "Chitipa district",
      "Ntcheu District",
      "Rumphi District",
      "Dowa District",
      "Karonga District",
      "Central Region",
      "Likoma District",
      "Kasungu District",
      "Nkhata Bay District",
      "Balaka District",
      "Dedza District",
      "Thyolo District",
      "Mchinji District",
      "Nkhotakota District",
      "Lilongwe District",
      "Blantyre District",
      "Mulanje District",
      "Mzimba District",
      "Northern Region",
      "Southern Region",
      "Chikwawa District",
      "Phalombe District",
      "Chiradzulu District",
      "Mangochi District",
      "Ntchisi District",
    ]
  },
  {
    "name": "Malaysia",
    "flag": "my.png",
    "code": "60",
    "states": [
      "Labuan",
      "Sabah",
      "Sarawak",
      "Perlis",
      "Penang",
      "Pahang",
      "Malacca",
      "Terengganu",
      "Perak",
      "Selangor",
      "Putrajaya",
      "Kelantan",
      "Kedah",
      "Negeri Sembilan",
      "Kuala Lumpur",
      "Johor",
    ],
  },
  {
    "name": "Maldives",
    "flag": "mv.png",
    "code": "960",
    "states": [
      "Vaavu Atoll",
      "Shaviyani Atoll",
      "Haa Alif Atoll",
      "Alif Alif Atoll",
      "North Province",
      "North Central Province",
      "Dhaalu Atoll",
      "Thaa Atoll",
      "Noonu Atoll",
      "Upper South Province",
      "Addu Atoll",
      "Gnaviyani Atoll",
      "Kaafu Atoll",
      "Haa Dhaalu Atoll",
      "Gaafu Alif Atoll",
      "Faafu Atoll",
      "Alif Dhaal Atoll",
      "Laamu Atoll",
      "Raa Atoll",
      "Gaafu Dhaalu Atoll",
      "Central Province",
      "South Province",
      "South Central Province",
      "Lhaviyani Atoll",
      "Meemu Atoll",
      "Malé",
    ]
  },
  {
    "name": "Mali",
    "flag": "ml.png",
    "code": "223",
    "states": [
      "Tombouctou Region",
      "Ségou Region",
      "Koulikoro Region",
      "Ménaka Region",
      "Kayes Region",
      "Bamako",
      "Sikasso Region",
      "Mopti Region",
      "Taoudénit Region",
      "Kidal Region",
      "Gao Region",
    ],
  },
  {
    "name": "Malta",
    "flag": "mt.png",
    "code": "356",
    "states": [
      "Mqabba",
      "San Ġwann",
      "Żurrieq",
      "Luqa",
      "Marsaxlokk",
      "Qala",
      "Żebbuġ Malta",
      "Xgħajra",
      "Kirkop",
      "Rabat",
      "Floriana",
      "Żebbuġ Gozo",
      "Swieqi",
      "Saint Lawrence",
      "Birżebbuġa",
      "Mdina",
      "Santa Venera",
      "Kerċem",
      "Għarb",
      "Iklin",
      "Santa Luċija",
      "Valletta",
      "Msida",
      "Birkirkara",
      "Siġġiewi",
      "Kalkara",
      "St. Julian's",
      "Victoria",
      "Mellieħa",
      "Tarxien",
      "Sliema",
      "Ħamrun",
      "Għasri",
      "Birgu",
      "Balzan",
      "Mġarr",
      "Attard",
      "Qrendi",
      "Naxxar",
      "Gżira",
      "Xagħra",
      "Paola",
      "Sannat",
      "Dingli",
      "Gudja",
      "Qormi",
      "Għargħur",
      "Xewkija",
      "Ta' Xbiex",
      "Żabbar",
      "Għaxaq",
      "Pembroke",
      "Lija",
      "Pietà",
      "Marsa",
      "Fgura",
      "Għajnsielem",
      "Mtarfa",
      "Munxar",
      "Nadur",
      "Fontana",
      "Żejtun",
      "Senglea",
      "Marsaskala",
      "Cospicua",
      "St. Paul's Bay",
    ]
  },
  {
    "name": "Mauritania",
    "flag": "mr.png",
    "code": "222",
    "states": [
      "Hodh Ech Chargui",
      "Brakna",
      "Tiris Zemmour",
      "Gorgol",
      "Inchiri",
      "Nouakchott-Nord",
      "Adrar",
      "Tagant",
      "Dakhlet Nouadhibou",
      "Nouakchott-Sud",
      "Trarza",
      "Assaba",
      "Guidimaka",
      "Hodh El Gharbi",
      "Nouakchott-Ouest",
    ]
  },
  {
    "name": "Mauritius",
    "flag": "mu.png",
    "code": "230",
    "states": [
      "Agaléga",
      "Rodrigues",
      "Pamplemousses District",
      "Cargados Carajos",
      "Vacoas-Phoenix",
      "Moka District",
      "Flacq District",
      "Curepipe",
      "Port Louis",
      "Savanne District",
      "Quatre Bornes",
      "Rivière Noire District",
      "Port Louis District",
      "Rivière du Rempart District",
      "Beau Bassin-Rose Hill",
      "Plaines Wilhems District",
      "Grand Port District",
    ]
  },
  {
    "name": "Mexico",
    "flag": "mx.png",
    "code": "52",
    "states": [
      "Chihuahua",
      "Oaxaca",
      "Sinaloa",
      "Estado de México",
      "Chiapas",
      "Nuevo León",
      "Durango",
      "Tabasco",
      "Querétaro",
      "Aguascalientes",
      "Baja California",
      "Tlaxcala",
      "Guerrero",
      "Baja California Sur",
      "San Luis Potosí",
      "Zacatecas",
      "Tamaulipas",
      "Veracruz",
      "Morelos",
      "Yucatán",
      "Quintana Roo",
      "Sonora",
      "Guanajuato",
      "Hidalgo",
      "Coahuila de Zaragoza",
      "Colima",
      "Ciudad de México",
      "Michoacán de Ocampo",
      "Campeche",
      "Puebla",
      "Nayarit",
      "Jalisco",
    ]
  },
  {
    "name": "Moldova",
    "flag": "md.png",
    "code": "373",
    "states": [
      "Cimișlia District",
      "Orhei District",
      "Bender",
      "Nisporeni District",
      "Sîngerei District",
      "Căușeni District",
      "Călărași District",
      "Glodeni District",
      "Anenii Noi District",
      "Ialoveni District",
      "Florești District",
      "Telenești District",
      "Taraclia District",
      "Chișinău",
      "Soroca District",
      "Briceni District",
      "Rîșcani District",
      "Strășeni District",
      "Ștefan Vodă District",
      "Basarabeasca District",
      "Cantemir District",
      "Fălești District",
      "Hîncești District",
      "Dubăsari District",
      "Dondușeni District",
      "Gagauzia",
      "Ungheni District",
      "Edineț District",
      "Șoldănești District",
      "Ocnița District",
      "Criuleni District",
      "Cahul District",
      "Drochia District",
      "Bălți",
      "Rezina District",
    ]
  },
  {
    "name": "Monaco",
    "flag": "mc.png",
    "code": "377",
    "states": [
      "La Colle",
      "La Condamine",
      "Les Moneghetti",
    ]
  },
  {
    "name": "Mongolia",
    "flag": "mn.png",
    "code": "976",
    "states": [
      "Bulgan Province",
      "Darkhan-Uul Province",
      "Dornod Province",
      "Khovd Province",
      "Övörkhangai Province",
      "Orkhon Province",
      "Ömnögovi Province",
      "Töv Province",
      "Bayan-Ölgii Province",
      "Dundgovi Province",
      "Uvs Province",
      "Govi-Altai Province",
      "Arkhangai Province",
      "Khentii Province",
      "Khövsgöl Province",
      "Bayankhongor Province",
      "Sükhbaatar Province",
      "Govisümber Province",
      "Zavkhan Province",
      "Selenge Province",
      "Dornogovi Province",
    ]
  },
  {
    "name": "Montenegro",
    "flag": "me.png",
    "code": "382",
    "states": [
      "Petnjica",
      "Bar",
      "Danilovgrad",
      "Rožaje",
      "Plužine",
      "Nikšić",
      "Šavnik",
      "Plav",
      "Pljevlja",
      "Berane",
      "Mojkovac",
      "Andrijevica",
      "Gusinje",
      "Bijelo Polje",
      "Kotor",
      "Podgorica",
      "Old Royal Capital Cetinje",
      "Tivat",
      "Budva",
      "Kolašin",
      "Žabljak",
      "Ulcinj",
    ]
  },
  {
    "name": "Mozambique",
    "flag": "mz.png",
    "code": "258",
    "states": [
      "Cabo Delgado Province",
      "Zambezia Province",
      "Gaza Province",
      "Inhambane Province",
      "Sofala Province",
      "Maputo Province",
      "Niassa Province",
      "Tete Province",
      "Maputo",
      "Nampula Province",
      "Manica Province",
    ]
  },
  {
    "name": "Myanmar",
    "flag": "mm.png",
    "code": "95",
    "states": [
      "Kayin State",
      "Mandalay Region",
      "Yangon Region",
      "Magway Region",
      "Chin State",
      "Rakhine State",
      "Shan State",
      "Tanintharyi Region",
      "Bago",
      "Ayeyarwady Region",
      "Kachin State",
      "Kayah State",
      "Sagaing Region",
      "Naypyidaw Union Territory",
      "Mon State",
    ]
  },
  {
    "name": "Namibia",
    "flag": "na.png",
    "code": "264",
    "states": [
      "Kunene Region",
      "Kavango West Region",
      "Kavango East Region",
      "Oshana Region",
      "Hardap Region",
      "Omusati Region",
      "Ohangwena Region",
      "Omaheke Region",
      "Oshikoto Region",
      "Erongo Region",
      "Khomas Region",
      "Karas Region",
      "Otjozondjupa Region",
      "Zambezi Region",
    ],
  },
  {
    "name": "Nepal",
    "flag": "np.png",
    "code": "977",
    "states": [
      "Mid-Western Region",
      "Western Region",
      "Far-Western Development Region",
      "Eastern Development Region",
      "Mechi Zone",
      "Bheri Zone",
      "Kosi Zone",
      "Central Region",
      "Lumbini Zone",
      "Narayani Zone",
      "Janakpur Zone",
      "Rapti Zone",
      "Seti Zone",
      "Karnali Zone",
      "Dhaulagiri Zone",
      "Gandaki Zone",
      "Bagmati Zone",
      "Mahakali Zone",
      "Sagarmatha Zone",
    ]
  },
  {
    "name": "Netherlands",
    "flag": "nl.png",
    "code": "31",
    "states": [
      "Utrecht",
      "Gelderland",
      "North Holland",
      "Drenthe",
      "South Holland",
      "Limburg",
      "Sint Eustatius",
      "Groningen",
      "Overijssel",
      "Flevoland",
      "Zeeland",
      "Saba",
      "Friesland",
      "North Brabant",
      "Bonaire",
    ]
  },
  {
    "name": "New Zealand",
    "flag": "nz.png",
    "code": "64",
    "states": [
      "Northland Region",
      "Manawatu-Wanganui Region",
      "Waikato Region",
      "Otago Region",
      "Marlborough Region",
      "West Coast Region",
      "Wellington Region",
      "Canterbury Region",
      "Chatham Islands",
      "Gisborne District",
      "Taranaki Region",
      "Nelson Region",
      "Southland Region",
      "Auckland Region",
      "Tasman District",
      "Bay of Plenty Region",
      "Hawke's Bay Region",
    ]
  },
  {
    "name": "Nicaragua",
    "flag": "ni.png",
    "code": "505",
    "states": [
      "Chontales",
      "Managua",
      "Rivas",
      "Granada",
      "León",
      "Estelí",
      "Boaco",
      "Matagalpa",
      "Madriz",
      "Río San Juan",
      "Carazo",
      "North Caribbean Coast",
      "South Caribbean Coast",
      "Masaya",
      "Chinandega",
      "Jinotega",
      "Nueva Segovia",
    ]
  },
  {
    "name": "Niger",
    "flag": "ne.png",
    "code": "227",
    "states": [
      "Tillabéri Region",
      "Dosso Region",
      "Zinder Region",
      "Maradi Region",
      "Agadez Region",
      "Diffa Region",
      "Tahoua Region",
    ]
  },
  {
    "name": "Nigeria",
    "flag": "ng.png",
    "code": "234",
    "states": [
      "Jigawa",
      "Enugu",
      "Kebbi",
      "Benue",
      "Sokoto",
      "Abuja Federal Capital Territory",
      "Kaduna",
      "Kwara",
      "Oyo",
      "Yobe",
      "Kogi",
      "Zamfara",
      "Kano",
      "Nasarawa",
      "Plateau",
      "Abia",
      "Akwa Ibom",
      "Bayelsa",
      "Lagos",
      "Borno",
      "Imo",
      "Ekiti",
      "Gombe",
      "Ebonyi",
      "Bauchi",
      "Katsina",
      "Cross River",
      "Anambra",
      "Delta",
      "Niger",
      "Edo",
      "Taraba",
      "Adamawa",
      "Ondo",
      "Osun",
      "Ogun",
      "Rivers",
    ]
  },
  {
    "name": "Norway",
    "flag": "no.png",
    "code": "47",
    "states": [
      "Trøndelag",
      "Oslo",
      "Vestfold",
      "Oppland",
      "Sør-Trøndelag",
      "Buskerud",
      "Nord-Trøndelag",
      "Svalbard",
      "Vest-Agder",
      "Troms",
      "Finnmark",
      "Akershus",
      "Sogn og Fjordane",
      "Hedmark",
      "Møre og Romsdal",
      "Rogaland",
      "Østfold",
      "Hordaland",
      "Telemark",
      "Nordland",
      "Jan Mayen",
    ]
  },
  {
    "name": "Oman",
    "flag": "om.png",
    "code": "968",
    "states": [
      "Ad Dhahirah",
      "Al Batinah North",
      "Al Batinah South",
      "Al Batinah Region",
      "Ash Sharqiyah Region",
      "Musandam",
      "Ash Sharqiyah North",
      "Ash Sharqiyah South",
      "Muscat",
      "Al Wusta",
      "Dhofar",
      "Ad Dakhiliyah",
      "Al Buraimi",
    ]
  },
  {
    "name": "Pakistan",
    "flag": "pk.png",
    "code": "92",
    "states": [
      "Islamabad Capital Territory",
      "Gilgit-Baltistan",
      "Khyber Pakhtunkhwa",
      "Azad Kashmir",
      "Balochistan",
      "Sindh",
      "Punjab",
    ]
  },
  {
    "name": "Panama",
    "flag": "pa.png",
    "code": "507",
    "states": [
      "Darién Province",
      "Colón Province",
      "Coclé Province",
      "Guna Yala",
      "Herrera Province",
      "Los Santos Province",
      "Ngöbe-Buglé Comarca",
      "Veraguas Province",
      "Bocas del Toro Province",
      "Panamá Oeste Province",
      "Panamá Province",
      "Emberá-Wounaan Comarca",
      "Chiriquí Province",
    ]
  },
  {
    "name": "Paraguay",
    "flag": "py.png",
    "code": "595",
    "states": [
      "Presidente Hayes",
      "Canindeyú",
      "Guairá",
      "Caaguazú",
      "Paraguarí",
      "Caazapá",
      "San Pedro",
      "Central",
      "Itapúa",
      "Concepción",
      "Boquerón",
      "Ñeembucú",
      "Amambay",
      "Cordillera",
      "Alto Paraná",
      "Alto Paraguay",
      "Misiones",
    ]
  },
  {
    "name": "Peru",
    "flag": "pe.png",
    "code": "51",
    "states": [
      "Madre de Dios",
      "Huancavelica",
      "Áncash",
      "Arequipa",
      "Puno",
      "La Libertad",
      "Ucayali",
      "Amazonas",
      "Pasco",
      "Huanuco",
      "Cajamarca",
      "Tumbes",
      "Cusco",
      "Ayacucho",
      "Junín",
      "San Martín",
      "Lima",
      "Tacna",
      "Piura",
      "Moquegua",
      "Apurímac",
      "Ica",
      "Callao",
      "Lambayeque",
      "Loreto",
    ]
  },
  {
    "name": "Philippines",
    "flag": "ph.png",
    "code": "63",
    "states": [
      "Romblon",
      "Bukidnon",
      "Rizal",
      "Bohol",
      "Quirino",
      "Biliran",
      "Quezon",
      "Siquijor",
      "Sarangani",
      "Bulacan",
      "Cagayan",
      "South Cotabato",
      "Sorsogon",
      "Sultan Kudarat",
      "Camarines Norte",
      "Southern Leyte",
      "Camiguin",
      "Surigao del Norte",
      "Camarines Sur",
      "Sulu",
      "Davao Oriental",
      "Eastern Samar",
      "Dinagat Islands",
      "Capiz",
      "Tawi-Tawi",
      "Calabarzon",
      "Tarlac",
      "Surigao del Sur",
      "Zambales",
      "Ilocos Norte",
      "Mimaropa",
      "Ifugao",
      "Catanduanes",
      "Zamboanga del Norte",
      "Guimaras",
      "Bicol",
      "Western Visayas",
      "Cebu",
      "Cavite",
      "Central Visayas",
      "Davao Occidental",
      "Soccsksargen",
      "Compostela Valley",
      "Kalinga",
      "Isabela",
      "Caraga",
      "Iloilo",
      "La Union",
      "Davao del Sur",
      "Davao del Norte",
      "Cotabato",
      "Ilocos Sur",
      "Eastern Visayas",
      "Agusan del Norte",
      "Abra",
      "Zamboanga Peninsula",
      "Agusan del Sur",
      "Lanao del Norte",
      "Laguna",
      "Marinduque",
      "Maguindanao",
      "Aklan",
      "Leyte",
      "Lanao del Sur",
      "Apayao",
      "Cordillera Administrative",
      "Antique",
      "Albay",
      "Masbate",
      "Northern Mindanao",
      "Davao",
      "Aurora",
      "Cagayan Valley",
      "Misamis Occidental",
      "Bataan",
      "Central Luzon",
      "Basilan",
      "Metro Manila",
      "Misamis Oriental",
      "Northern Samar",
      "Negros Oriental",
      "Negros Occidental",
      "Batanes",
      "Mountain Province",
      "Oriental Mindoro",
      "Ilocos",
      "Occidental Mindoro",
      "Zamboanga del Sur",
      "Nueva Vizcaya",
      "Batangas",
      "Nueva Ecija",
      "Palawan",
      "Zamboanga Sibugay",
      "Benguet",
      "Pangasinan",
      "Pampanga",
      "Western Samar",
    ]
  },
  {
    "name": "Poland",
    "flag": "pl.png",
    "code": "48",
    "states": [
      "Opole",
      "Silesian",
      "Pomeranian",
      "Kuyavian-Pomeranian",
      "Podkarpackie",
      "Warmian-Masurian",
      "Lower Silesian",
      "Świętokrzyskie",
      "Lubusz",
      "Podlaskie",
      "West Pomeranian",
      "Greater Poland",
      "Lesser Poland",
      "Łódź",
      "Masovian",
      "Lublin",
    ]
  },
  {
    "name": "Portugal",
    "flag": "pt.png",
    "code": "351",
    "states": [
      "Lisbon",
      "Bragança",
      "Beja",
      "Madeira",
      "Portalegre",
      "Açores",
      "Vila Real",
      "Aveiro",
      "Évora",
      "Viseu",
      "Santarém",
      "Faro",
      "Leiria",
      "Castelo Branco",
      "Setúbal",
      "Porto",
      "Braga",
      "Viana do Castelo",
      "Coimbra",
      "Guarda",
    ]
  },
  {
    "name": "Qatar",
    "flag": "qa.png",
    "code": "974",
    "states": [
      "Al Rayyan",
      "Al-Shahaniya",
      "Al Wakrah",
      "Madinat ash Shamal",
      "Doha",
      "Al Daayen",
      "Al Khor",
      "Umm Salal",
    ]
  },
  {
    "name": "Romania",
    "flag": "ro.png",
    "code": "40",
    "states": [
      "Suceava",
      "Hunedoara",
      "Arges",
      "Bihor",
      "Alba",
      "Ilfov",
      "Giurgiu",
      "Tulcea",
      "Teleorman",
      "Prahova",
      "Bucharest",
      "Neamț",
      "Călărași",
      "Bistrița-Năsăud",
      "Cluj",
      "Iași",
      "Braila",
      "Constanța",
      "Olt",
      "Arad",
      "Botoșani",
      "Sălaj",
      "Dolj",
      "Ialomița",
      "Bacău",
      "Dâmbovița",
      "Satu Mare",
      "Galați",
      "Timiș",
      "Harghita",
      "Gorj",
      "Mehedinți",
      "Vaslui",
      "Caraș-Severin",
      "Covasna",
      "Sibiu",
      "Buzău",
      "Vâlcea",
      "Vrancea",
      "Brașov",
      "Maramureș",
      "Mureș",
    ]
  },
  {
    "name": "Russia",
    "flag": "ru.png",
    "code": "7",
    "states": [
      "Primorsky Krai",
      "Novgorod Oblast",
      "Jewish Autonomous Oblast",
      "Nenets Autonomous Okrug",
      "Rostov Oblast",
      "Khanty-Mansi Autonomous Okrug",
      "Magadan Oblast",
      "Krasnoyarsk Krai",
      "Republic of Karelia",
      "Republic of Buryatia",
      "Murmansk Oblast",
      "Kaluga Oblast",
      "Chelyabinsk Oblast",
      "Omsk Oblast",
      "Yamalo-Nenets Autonomous Okrug",
      "Sakha Republic",
      "Arkhangelsk",
      "Republic of Dagestan",
      "Yaroslavl Oblast",
      "Republic of Adygea",
      "Republic of North Ossetia-Alania",
      "Republic of Bashkortostan",
      "Kursk Oblast",
      "Ulyanovsk Oblast",
      "Nizhny Novgorod Oblast",
      "Amur Oblast",
      "Chukotka Autonomous Okrug",
      "Tver Oblast",
      "Republic of Tatarstan",
      "Samara Oblast",
      "Pskov Oblast",
      "Ivanovo Oblast",
      "Kamchatka Krai",
      "Astrakhan Oblast",
      "Bryansk Oblast",
      "Stavropol Krai",
      "Karachay-Cherkess Republic",
      "Mari El Republic",
      "Perm Krai",
      "Tomsk Oblast",
      "Khabarovsk Krai",
      "Vologda Oblast",
      "Sakhalin",
      "Altai Republic",
      "Republic of Khakassia",
      "Tambov Oblast",
      "Saint Petersburg",
      "Irkutsk",
      "Vladimir Oblast",
      "Moscow Oblast",
      "Republic of Kalmykia",
      "Republic of Ingushetia",
      "Smolensk Oblast",
      "Orenburg Oblast",
      "Saratov Oblast",
      "Novosibirsk",
      "Lipetsk Oblast",
      "Kirov Oblast",
      "Krasnodar Krai",
      "Kabardino-Balkar Republic",
      "Chechen Republic",
      "Sverdlovsk",
      "Tula Oblast",
      "Leningrad Oblast",
      "Kemerovo Oblast",
      "Republic of Mordovia",
      "Komi Republic",
      "Tuva Republic",
      "Moscow",
      "Kaliningrad",
      "Belgorod Oblast",
      "Zabaykalsky Krai",
      "Ryazan Oblast",
      "Voronezh Oblast",
      "Tyumen Oblast",
      "Oryol Oblast",
      "Penza Oblast",
      "Kostroma Oblast",
      "Altai Krai",
      "Sevastopol",
      "Udmurt Republic",
      "Chuvash Republic",
      "Kurgan Oblast",
      "Volgograd Oblast",
    ]
  },
  {
    "name": "Rwanda",
    "flag": "rw.png",
    "code": "250",
    "states": [
      "Southern Province",
      "Western Province",
      "Eastern Province",
      "Kigali district",
      "Northern Province",
    ]
  },
  {
    "name": "Saudi Arabia",
    "flag": "sa.png",
    "code": "966",
    "states": [
      "Riyadh",
      "Makkah",
      "Al Madinah",
      "Tabuk",
      "'Asir",
      "Northern Borders",
      "Ha'il",
      "Eastern Province",
      "Al Jawf",
      "Jizan",
      "Al Bahah",
      "Najran",
      "Al-Qassim",
    ]
  },
  {
    "name": "Senegal",
    "flag": "sn.png",
    "code": "221",
    "states": [
      "Dakar",
      "Kolda",
      "Kaffrine",
      "Matam",
      "Saint-Louis",
      "Ziguinchor",
      "Fatick",
      "Diourbel Region",
      "Kédougou",
      "Sédhiou",
      "Kaolack",
      "Thiès Region",
      "Louga",
      "Tambacounda Region",
    ]
  },
  {
    "name": "Serbia",
    "flag": "rs.png",
    "code": "381",
    "states": [
      "South Bačka District",
      "Pirot District",
      "South Banat District",
      "North Bačka District",
      "Jablanica District",
      "Central Banat District",
      "Bor District",
      "Toplica District",
      "Mačva District",
      "Rasina District",
      "Pčinja District",
      "Nišava District",
      "Kolubara District",
      "Raška District",
      "West Bačka District",
      "Moravica District",
      "Belgrade",
      "Zlatibor District",
      "Zaječar District",
      "Braničevo District",
      "Vojvodina",
      "Šumadija District",
      "North Banat District",
      "Pomoravlje District",
      "Srem District",
      "Podunavlje District",
    ]
  },
  {
    "name": "Sierra Leone",
    "flag": "sl.png",
    "code": "232",
    "states": [
      "Northern Province",
      "Southern Province",
      "Western Area",
      "Eastern Province",
    ]
  },
  {
    "name": "Singapore",
    "flag": "sg.png",
    "code": "65",
    "states": [
      "North East",
      "South East",
      "Central Singapore",
      "North West",
    ]
  },
  // START FROM SLOVAKIA...WAITING
];
